### ISSUE TITLE
rename the worksheets

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/data-science-a-first-intro-worksheets#1]
The worksheet numbers don't correspond to chapter numbers. We should eventually

- rename the worksheets to be human-interpretable (e.g. `worksheet_02.ipynb` -> `worksheet_reading.ipynb`)
- update the links in the textbook repo to the new ones

**Comment by ttimbers** [comment]
I think we should do this for the course too...

**Comment by ttimbers** [comment]
Thinking more on this, we should only do this here if we do this in the course. I imagine this as a living repo, where when we fix things in the course, we bring those changes in here. So that will not flow as easily (and we will introduce errors) if we use two different naming conventions. So I propose in summer 2022 we make this change in both places?

**Comment by trevorcampbell** [comment]
I'd be on board to do it in the next few weeks before the upcoming semester. It's an easy change to make and we may as well take care of it before publication (because the links will need to be static after that point!).
