### ISSUE TITLE
Outdated R packages not compatible with JupyterLab v4.0.1

### ISSUE THREAD

**Issue by GaryHilares** [UBC-DSCI/data-science-a-first-intro-worksheets#7]
In chapter 13 is recommended to install the R packages in the `environment.yml` file using the command `conda env update --file https://raw.githubusercontent.com/UBC-DSCI/data-science-a-first-intro-worksheets/main/environment.yml`. However, when I tested this method it did not work with the current Jupyter notebook version (it threw an error message Jupyter notebook could not reach the IRkernel). To get a working instance I had to install the latest packages using the `conda install -c conda-forge -y  r-base  r-cowplot  r-ggally  r-gridextra  r-irkernel  r-kknn  r-rpostgres  r-rsqlite  r-scales  r-testthat  r-tidymodels  r-tidyverse  r-tinytex  unixodbc` command.

In Binder this does not look like an issue because Binder uses JupyterLab v3.1.12. However, as of 2023-06-06, the instructions for local installation use JupyterLab v4.0.1. I would recommend updating the R packages' versions for compatibility with the latest Jupyter Lab version. Another possible solution would be to add instructions to instructions to install JupyterLab v3.1.12 rather than v4.0.1. I personally prefer the first approach.

Tested in Ubuntu 22.04.1 LTS.

**Comment by trevorcampbell** [comment]
Thanks for the heads up @GaryHilares . I'm planning to do a round of edits on the textbook/worksheets this summer at some point, so I'll make sure to revisit this when I do.

**Comment by trevorcampbell** [comment]
FYI: I've been working on the textbook/worksheets/etc for the past few weeks. Due to various dependencies we have (most notably, nbgrader and autotest), we can't update to JLab 4+ yet. It looks like nbgrader  [should be compatible shortly](https://github.com/jupyter/nbgrader/discussions/1749), but autotest won't likely be compatible [until this PR is merged](https://github.com/jupyter/nbgrader/pull/1650) or at least brought up to speed with nbgrader 0.9.x.

I'll leave this open until that is resolved.
